# Generated by Django 6.1.1 on 2026-09-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('station_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('price_min', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('source_rows', models.PositiveIntegerField(default=1)),
                ('price_outlier', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='station_coordinates_idx'), models.Index(fields=['state', 'city'], name='station_locality_idx')],
            },
        ),
    ]
